// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notes_ESPI_en_mieux.Entities;

#nullable disable

namespace Notes_ESPI_en_mieux.Migrations
{
    [DbContext(typeof(NotesEpsiEnMieuxContext))]
    [Migration("20240201135900_initdb")]
    partial class initdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Notes_ESPI_en_mieux.Entities.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("classe", (string)null);
                });

            modelBuilder.Entity("Notes_ESPI_en_mieux.Entities.Cours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("IdProf")
                        .HasColumnType("int")
                        .HasColumnName("ID_Prof");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdProf" }, "ID_Prof");

                    b.ToTable("cours", (string)null);
                });

            modelBuilder.Entity("Notes_ESPI_en_mieux.Entities.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("IdCours")
                        .HasColumnType("int")
                        .HasColumnName("ID_Cours");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCours" }, "ID_Cours");

                    b.ToTable("evaluation", (string)null);
                });

            modelBuilder.Entity("Notes_ESPI_en_mieux.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("Coefficient")
                        .HasColumnType("int");

                    b.Property<int?>("IdEleve")
                        .HasColumnType("int")
                        .HasColumnName("ID_Eleve");

                    b.Property<int?>("IdEvaluation")
                        .HasColumnType("int")
                        .HasColumnName("ID_Evaluation");

                    b.Property<float?>("Valeur")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEleve" }, "ID_Eleve");

                    b.HasIndex(new[] { "IdEvaluation" }, "ID_Evaluation");

                    b.ToTable("note", (string)null);
                });

            modelBuilder.Entity("Notes_ESPI_en_mieux.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("IdClasse")
                        .HasColumnType("int")
                        .HasColumnName("ID_classe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdClasse" }, "ID_classe");

                    b.ToTable("user", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
